routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::resource('pertanyaan', 'PertanyaanController');

// Route::get('/pertanyaan/create', 'PertanyaanController@create');
// Route::post('/pertanyaan', 'PertanyaanController@store');
// Route::get('/pertanyaan', 'PertanyaanController@index')->name('pertanyaan.index');
// Route::get('/pertanyaan/{id}', 'PertanyaanController@show');
// Route::get('/pertanyaan/{id}/edit', 'PertanyaanController@edit');
// Route::put('/pertanyaan/{id}', 'PertanyaanController@update');
// Route::delete('/pertanyaan/{id}', 'PertanyaanController@destroy');

// Route::get('/', function() {
//     return view('welcome');
// });

// Route::get('/data-tables', function() {
//     return view('items.datatabel');
// });

// Route::get('/', function () {
//     return view('welcome');
// });

// Route::get('/home', 'FormConroller@home');
// Route::get('/form', 'FormConroller@register');

// Route::post('/selamatdatang', 'FormConroller@sapa');

// Route::get('/master', function() {
//     return view('adminlte.master');
// });

// Route::get('/items', function() {
//     return view('items.index');
// });

// Route::get('/items/create', function() {
//     return view('items.create');
//  });

app/Pertanyaan.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Pertanyaan extends Model
{
    // cara Eloquent
    protected $table = "questions";

    // cara Mass Assignment
    // protected $fillable = ["title", "body"];

    // Cara Guarded -> kebalikan dr Mass Ass.
    protected $guarded = []; // yg di blacklist kosong atau semua tabel diisi
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/FormConroller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class FormConroller extends Controller
{
    public function home() {
        return view('home');
    }

    public function register() {
        return view('form');
    }

    public function sapa(Request $request) {
        $nama = $request["namadepan"] . " " . $request["namabelakang"];
        return "<h1>SELAMAT DATANG $nama !</h1>" . view('selamatdatang');
    }
}

app/Http/Controllers/PertanyaanController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use DB;
use App\Pertanyaan;

class PertanyaanController extends Controller
{
    public function create() {
        // menampilkan form untuk membuat pertanyaan baru
        return view('pertanyaan.create');
    }

    public function store(Request $request) {
        // menyimpan data baru ke tabel pertanyaan
        // dd($request->all());
        $request->validate([
            'title' => 'required|unique:questions',
            'body' => 'required'
        ]);
        // Cara Eloquent
        // $pertanyaan = objek baru dr kelas Pertanyaan
        // $pertanyaan = new Pertanyaan;
        // $pertanyaan->title = $request["title"];
        // $pertanyaan->body = $request["body"];
        // $pertanyaan->save(); // insert into pertanyaan (title, body) values

        // $query = DB::table('questions')->insert([
        //     'title' => $request['title'],
        //     'body' => $request['body']
        // ]);
        
        // cara Mass Assignment => semua kolom pd tabel dijabarin satu2 seperti ini :
        $pertanyaan = Pertanyaan::create([
            "title" => $request["title"],
            "body" => $request["body"]
        ]);

        return redirect('/pertanyaan')->with('success', 'Post Berhasil Disimpan!');
    }

    public function index() {
        // menampilkan list data pertanyaan-pertanyaan 
        // (boleh menggunakan table html atau bootstrap card)
        // $posts = DB::table('questions')->get();
        // dd($posts);

        
        // Eloquent
        $posts = Pertanyaan::all();
        return view('pertanyaan.index', compact('posts')); // compact('variabel')
    }

    public function show($id) {
        // menampilkan detail pertanyaan dengan id tertentu
        // $post = DB::table('questions')->where('id', $id)->first();

        // Eloquent
        $post = Pertanyaan::find($id); // bs pakek find atau where. Baca di laravel.com
        // dd($post);
        return view('pertanyaan.show', compact('post'));
    }

    public function edit($id) {
        // menampilkan form untuk edit pertanyaan dengan id tertentu
        // $post = DB::table('questions')->where('id', $id)->first();
        
        // Eloquent
        $post = Pertanyaan::find($id);
        
        return view('pertanyaan.edit', compact('post'));
    }

    public function update($id, Request $request) {
        // menyimpan perubahan data pertanyaan (update) untuk id tertentu
        // $request->validate([
        //     'title' => 'required|unique:questions',
        //     'body' => 'required'
        // ]);

        // $query = DB::table('questions')
        //         ->where('id', $id)
        //         ->update([
        //             'title' => $request['title'],
        //             'body' => $request['body']
        //         ]);

        // Cara Eloquent
        $update = Pertanyaan::where('id', $id)->update([
            "title" => $request["title"],
            "body" => $request["body"]
        ]);
        
        return redirect('/pertanyaan')->with('success', "Berhasil Update Post!");
    }

    public function destroy($id) {
        // menghapus pertanyaan dengan id tertentu
        // $query = DB::table('questions')->where('id', $id)->delete();

        // Cara Eloquent
        Pertanyaan::destroy($id);
        return redirect('/pertanyaan')->with('success', "Post Berhasil dihapus!");
    }
}

app/Http/Controllers/PostingController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class PostingController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/adminlte/master.blade.php
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>AdminLTE 3 | Blank Page</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- Font Awesome -->
  <!-- {{ asset('') }} mewakili folder public -->
  <link rel="stylesheet" href=" {{ asset('/adminlte/plugins/fontawesome-free/css/all.min.css') }} ">
  <!-- Ionicons -->
  <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
  <!-- overlayScrollbars -->
  <link rel="stylesheet" href=" {{ asset('/adminlte/dist/css/adminlte.min.css') }} ">
  <!-- Google Font: Source Sans Pro -->
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
</head>
<body class="hold-transition sidebar-mini">
<!-- Site wrapper -->
<div class="wrapper">
  <!-- Navbar -->
  @include('adminlte.partials.navbar')
  <!-- /.navbar -->

  <!-- Main Sidebar Container -->
  @include('adminlte.partials.sidebar')

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    @yield('content')
  </div>
  <!-- /.content-wrapper -->

  <footer class="main-footer">
    <div class="float-right d-none d-sm-block">
      <b>Version</b> 3.0.5
    </div>
    <strong>Copyright &copy; 2014-2019 <a href="http://adminlte.io">AdminLTE.io</a>.</strong> All rights
    reserved.
  </footer>

  <!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
  </aside>
  <!-- /.control-sidebar -->
</div>
<!-- ./wrapper -->

<!-- jQuery -->
<script src="{{ asset('/adminlte/plugins/jquery/jquery.min.js') }}"></script>
<!-- Bootstrap 4 -->
<script src="{{ asset('/adminlte/plugins/bootstrap/js/bootstrap.bundle.min.js') }}"></script>
<!-- AdminLTE App -->
<script src="{{ asset('/adminlte/dist/js/adminlte.min.js') }}"></script>
<!-- AdminLTE for demo purposes -->
<script src="{{ asset('/adminlte/dist/js/demo.js') }}"></script>

@stack('scripts')

</body>
</html>

resources/views/adminlte/partials/navbar.blade.php
<nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="../../index3.html" class="nav-link">Home</a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="#" class="nav-link">Contact</a>
      </li>
    </ul>

    <!-- SEARCH FORM -->
    <form class="form-inline ml-3">
      <div class="input-group input-group-sm">
        <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
        <div class="input-group-append">
          <button class="btn btn-navbar" type="submit">
            <i class="fas fa-search"></i>
          </button>
        </div>
      </div>
    </form>

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
      <!-- Messages Dropdown Menu -->
      <li class="nav-item dropdown">
        <a class="nav-link" data-toggle="dropdown" href="#">
          <i class="far fa-comments"></i>
          <span class="badge badge-danger navbar-badge">3</span>
        </a>
        <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
          <a href="#" class="dropdown-item">
            <!-- Message Start -->
            <div class="media">
              <img src="../../dist/img/user1-128x128.jpg" alt="User Avatar" class="img-size-50 mr-3 img-circle">
              <div class="media-body">
                <h3 class="dropdown-item-title">
                  Brad Diesel
                  <span class="float-right text-sm text-danger"><i class="fas fa-star"></i></span>
                </h3>
                <p class="text-sm">Call me whenever you can...</p>
                <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
              </div>
            </div>
            <!-- Message End -->
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <!-- Message Start -->
            <div class="media">
              <img src="../../dist/img/user8-128x128.jpg" alt="User Avatar" class="img-size-50 img-circle mr-3">
              <div class="media-body">
                <h3 class="dropdown-item-title">
                  John Pierce
                  <span class="float-right text-sm text-muted"><i class="fas fa-star"></i></span>
                </h3>
                <p class="text-sm">I got your message bro</p>
                <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
              </div>
            </div>
            <!-- Message End -->
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <!-- Message Start -->
            <div class="media">
              <img src="../../dist/img/user3-128x128.jpg" alt="User Avatar" class="img-size-50 img-circle mr-3">
              <div class="media-body">
                <h3 class="dropdown-item-title">
                  Nora Silvester
                  <span class="float-right text-sm text-warning"><i class="fas fa-star"></i></span>
                </h3>
                <p class="text-sm">The subject goes here</p>
                <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
              </div>
            </div>
            <!-- Message End -->
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item dropdown-footer">See All Messages</a>
        </div>
      </li>
      <!-- Notifications Dropdown Menu -->
      <li class="nav-item dropdown">
        <a class="nav-link" data-toggle="dropdown" href="#">
          <i class="far fa-bell"></i>
          <span class="badge badge-warning navbar-badge">15</span>
        </a>
        <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
          <span class="dropdown-item dropdown-header">15 Notifications</span>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="fas fa-envelope mr-2"></i> 4 new messages
            <span class="float-right text-muted text-sm">3 mins</span>
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="fas fa-users mr-2"></i> 8 friend requests
            <span class="float-right text-muted text-sm">12 hours</span>
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="fas fa-file mr-2"></i> 3 new reports
            <span class="float-right text-muted text-sm">2 days</span>
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item dropdown-footer">See All Notifications</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link" data-widget="control-sidebar" data-slide="true" href="#" role="button">
          <i class="fas fa-th-large"></i>
        </a>
      </li>
    </ul>
  </nav>

resources/views/form.blade.php
<!DOCTYPE html>
<html>
<head>
	<title>Form</title>
</head>
<body>

<h2>Buat Account Baru!</h2>
<h4>Sign Up Form</h4>

<form action="/selamatdatang" method="POST">
@csrf
<div>
	First name: <br />
	<br />
	<input type="text" name="namadepan" required placeholder="masukkan nama depan" /><br />
	<br />

	Last name: <br />
	<br />
	<input type="text" name="namabelakang" required placeholder="masukkan nama belakang" /><br />
	<br />
</div>

<div>
	Gender: <br />
	<br />

	<input type="radio" name="kelamin" value="male" />
	Male
	<br />

	<input type="radio" name="kelamin" value="female" />
	Female
	<br />

	<input type="radio" name="kelamin" value="other" />
	Other
</div>

<div>
	<br />
	Nationality: <br />
	<br />

	<select name="kewarganegaraan">
		<option value="indonesian">Indonesian</option><br />
		<br />
		
		<option value="singaporean">Singaporean</option><br />
		<br />
		
		<option value="italian">Italian</option><br />
		<br />
		
		<option value="australian">Australian</option>
	</select>
</div>
	
<div>
	<br />
	Language Spoken: <br />
	<br />

	<input type="checkbox" name="bahasaindonesia" />
	Bahasa Indonesia
	<br />

	<input type="checkbox" name="english" />
	English
	<br />

	<input type="checkbox" name="other" />
	Other
</div>

<div>
	<br />
	Bio: <br />
	<br />
	<textarea name="bio" rows="11" cols="33">
		
	</textarea>
	<br />

</div>

	<input type="submit" value="Sign Up" />

</form>

</body>
</html>

resources/views/home.blade.php
<!DOCTYPE html>
<html>
<head>
	<title>Index</title>
</head>
<body>

<h1>SanberBook</h1>
<h2>Social Media Developer Santai Berkualitas</h2>

<div>Belajar dan Berbagi agar hidup ini semakin santai berkualitas</div>

<h3>Benefit Join di SanberBook</h3>

<ul>
	<li>Mendapatkan motivasi dari sesama developer</li>
	<li>Ssharing knowledge dari para mastah sanber</li>
	<li>Dibuat oleh calon web developer terbaik</li>
</ul>

<h3>Cara Bergabung ke SanberBook</h3>
<ol style="list-style-type: decimal">
	<li>Mengunjungi Website ini</li>
	<li>Mendaftar di <a href="/form">Form Sign Up</a></li>
	<li>Selesai!</li>
</ol>

</body>
</html>

resources/views/items/create.blade.php
@extends('adminlte.master')

@section('content')
    <h2>halaman create</h2>
@endsection

@push('scripts')
<script>

 var wrappers = document.getElementsByClassName("wrappers");
 var items = ["ini", "contoh"];

console.log("ini items: ", items)
</script>
@endpush

resources/views/items/index.blade.php
@extends('adminlte.master')

@section('content')

<h1>OJO KEDUNYAN !</h1>

@endsection

resources/views/items/tabel.blade.php
@extends('adminlte.master')

@section('content')
<table class="table table-bordered">
  <thead>                  
    <tr>
      <th style="width: 10px">#</th>
      <th>Task</th>
      <th>Progress</th>
      <th style="width: 40px">Label</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>1.</td>
      <td>Update software</td>
      <td>
        <div class="progress progress-xs">
          <div class="progress-bar progress-bar-danger" style="width: 55%"></div>
        </div>
      </td>
      <td><span class="badge bg-danger">55%</span></td>
    </tr>
    <tr>
      <td>2.</td>
      <td>Clean database</td>
      <td>
        <div class="progress progress-xs">
          <div class="progress-bar bg-warning" style="width: 70%"></div>
        </div>
      </td>
      <td><span class="badge bg-warning">70%</span></td>
    </tr>
    <tr>
      <td>3.</td>
      <td>Cron job running</td>
      <td>
        <div class="progress progress-xs progress-striped active">
          <div class="progress-bar bg-primary" style="width: 30%"></div>
        </div>
      </td>
      <td><span class="badge bg-primary">30%</span></td>
    </tr>
    <tr>
      <td>4.</td>
      <td>Fix and squish bugs</td>
      <td>
        <div class="progress progress-xs progress-striped active">
          <div class="progress-bar bg-success" style="width: 90%"></div>
        </div>
      </td>
      <td><span class="badge bg-success">90%</span></td>
    </tr>
  </tbody>
</table>
@endsection

resources/views/pertanyaan/create.blade.php
@extends('adminlte.master');

@section('content')
    <div class="ml-3 mt-3">
        <div class="card card-primary">
            <div class="card-header">
                <h3 class="card-title">Create New Post</h3>
            </div>
            <!-- /.card-header -->
            <!-- form start -->
            <form role="form" action="/pertanyaan" method="POST">
            @csrf
                <div class="card-body">
                    <div class="form-group">
                        <label for="title">Title</label>
                        <input type="text" class="form-control" id="title" name="title" value=" {{ old('title', '') }} " placeholder="Enter Title">
                        @error('title')
                            <div class="alert alert-danger">{{ $message }}</div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="body">Body</label>
                        <input type="text" class="form-control" id="body" name="body" value=" {{ old('body', '') }} " placeholder="Body">
                        @error('body')
                            <div class="alert alert-danger">{{ $message }}</div>
                        @enderror
                    </div>
                </div>
                <!-- /.card-body -->

                <div class="card-footer">
                    <button type="submit" class="btn btn-primary">Create</button>
                </div>
            </form>
        </div>
    </div>

@endsection

resources/views/pertanyaan/edit.blade.php
@extends('adminlte.master');

@section('content')
    <div class="ml-3 mt-3">
        <div class="card card-primary">
            <div class="card-header">
                <h3 class="card-title">Update Post {{ $post->id }}</h3>
            </div>
            <!-- /.card-header -->
            <!-- form start -->
            <form role="form" action="/pertanyaan/{{ $post->id }}" method="POST">
            @csrf
            @method('PUT')
                <div class="card-body">
                    <div class="form-group">
                        <label for="title">Title</label>
                        <input type="text" class="form-control" id="title" name="title" value=" {{ old('title', $post->title) }} " placeholder="Enter Title">
                        @error('title')
                            <div class="alert alert-danger">{{ $message }}</div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="body">Body</label>
                        <input type="text" class="form-control" id="body" name="body" value=" {{ old('body', $post->body) }} " placeholder="Body">
                        @error('body')
                            <div class="alert alert-danger">{{ $message }}</div>
                        @enderror
                    </div>
                </div>
                <!-- /.card-body -->

                <div class="card-footer">
                    <button type="submit" class="btn btn-primary">Create</button>
                </div>
            </form>
        </div>
    </div>

@endsection

resources/views/pertanyaan/index.blade.php
@extends('adminlte.master');

@section('content')
    <div class="mt-3 ml-3">
    <div class="card">
        <div class="card-header">
            <h3 class="card-title">Questions Table</h3>
        </div>
        <!-- /.card-header -->
        <div class="card-body">
        @if(session('success'))
            <div class="alert alert-success">
                {{ session('success') }}
            </div>
        @endif

        <!-- Cara Query Builder -->
        <!-- <a class="btn btn-primary mb-3" href="/pertanyaan/create">Create New Post</a> -->
        
        <!-- Cara Eloquent -->
        <a class="btn btn-primary mb-3" href="{{ route('pertanyaan.create') }}">Create New Post</a>

            <table class="table table-bordered">
                <thead>                  
                    <tr>
                        <th style="width: 10px">#</th>
                        <th>Title</th>
                        <th>Body</th>
                        <th style="width: 40px">Action</th>
                    </tr>
                </thead>
                <tbody>
                <!-- object = $post . property = title -->
                    @forelse($posts as $key => $post) 
                    <tr>
                        <td> {{ $key + 1 }} </td>
                        <td> {{ $post->title }} </td>
                        <td> {{ $post->body }} </td>
                        <td>
                            <!-- <a href="/pertanyaan/{{$post->id}}" class="btn btn-info btn-sm">show</a> -->
                            <a href="{{ route('pertanyaan.show', ['pertanyaan' => $post->id]) }}" class="btn btn-info btn-sm">show</a>
                            
                            <!-- <a href="/pertanyaan/{{$post->id}}/edit" class="btn btn-info btn-sm ml-2">edit</a> -->
                            <a href="{{ route('pertanyaan.edit', ['pertanyaan' => $post->id]) }}" class="btn btn-info btn-sm ml-2">edit</a>
                            
                            <!-- <form action="/pertanyaan/{{$post->id}}" method="post"> -->
                            <form action="{{ route('pertanyaan.destroy', ['pertanyaan' => $post->id]) }}" method="post">
                            @csrf
                            @method('DELETE')
                                <input type="submit" value="delete" class="btn btn-danger btn-sm mt-2">
                            </form>
                        </td>
                    </tr>
                    @empty
                    <tr>
                        <td colspan="4" align="center"> No Posts </td>
                    </tr>
                    @endforelse
                </tbody>
            </table>
            </div>
            <!-- /.card-body -->
            <!-- <div class="card-footer clearfix">
                <ul class="pagination pagination-sm m-0 float-right">
                    <li class="page-item"><a class="page-link" href="#">«</a></li>
                    <li class="page-item"><a class="page-link" href="#">1</a></li>
                    <li class="page-item"><a class="page-link" href="#">2</a></li>
                    <li class="page-item"><a class="page-link" href="#">3</a></li>
                    <li class="page-item"><a class="page-link" href="#">»</a></li>
                </ul>
            </div> -->
    </div>
    </div>
@endsection

resources/views/pertanyaan/show.blade.php
@extends('adminlte.master');

@section('content')
    <div class="mt-3 ml-3">
        <h4> {{ $post->title }} </h4>
        <p> {{ $post->body }} </p>
    </div>
        
@endsection

resources/views/selamatdatang.blade.php
<!DOCTYPE html>
<html>
<head>
	<title>Welcome</title>
</head>
<body>

<h4>Terima kasih telah bergabung di SanberBook. Social Media kita bersama!</h4>

</body>
</html>